language: swift
osx_image: xcode8.3
xcode_project: TweenKit.xcodeproj
xcode_scheme: TweenKit
xcode_sdk: iphonesimulator10.1

script: xcodebuild test -project TweenKit/TweenKit.xcodeproj -scheme TweenKit -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
