language: swift
osx_image: xcode10
xcode_project: TweenKit.xcodeproj
xcode_scheme: TweenKit
xcode_sdk: iphonesimulator10.1

script: xcodebuild test -project TweenKit/TweenKit.xcodeproj -scheme TweenKit -sdk iphonesimulator -destination "name=iPhone SE"
